---
- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: install Docker
      include_role:
        name: docker

    - name: install K8s
      include_role:
        name: kubectl